### ISSUE TITLE
Kingdom Hearts 2 names is missing

### ISSUE THREAD

**Issue by gledson999** [GrzybDev/KingdomHeartsTool#10]
Incredible improvement you done using names, but you forgot to implement names for KH2, so i'm attaching for you the list names for Kingdom Hearts 2 below

[kh2idx.txt](https://github.com/GrzybDev/KingdomHeartsTool/files/6447233/kh2idx.txt)

**Comment by GrzybDev** [comment]
Hi!
Thank you for your contribution, where did you got this file?

Cheers

**Comment by gledson999** [comment]
Hi man, I found on Openkh resource too, I contributed to discover somes hashes.

[here](https://github.com/Xeeynamo/OpenKh/blob/ce262d5ea51daca339fb552ab0863bfd2eb07ef0/OpenKh.Kh2/resources/kh2idx.txt)

**Comment by GrzybDev** [comment]
Thank you again, kh2 filenames should work now :)
