### ISSUE TITLE
key is None type when packing kh1_first files

### ISSUE THREAD

**Issue by marxromper** [GrzybDev/KingdomHeartsTool#12]
**Describe the bug**
Packing fails because of "key" being None type in **Encryption.get_chunk** function. 

**To Reproduce**
1. khtool -p .\output\kh1_first.json -o .\output\kh1_first -v
2. Wait
3. See the error

**Expected behavior**
Packing is success full and the file can be used.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python 3.9

**Additional context**
Error got fixed when modified **__write_subentries_header**  function in the pack.py file by changing all the **subentry["compressed_file_size"]** to **entry["compressed_file_size"]** instead.

Not sure if this fix will ensure correct behaviour for all the files.

Modified function:
```python
    def __write_subentries_header(self, pkg, entry, key):
        if entry["subentries_count"] == 0:
            return None

        with open(self.inPath + self.names.get_name(entry["key"]) + "_data/entries.json") as entries_file:
            entries = json.load(entries_file)

        files = {}

        for subentryID in entries:
            subentry = entries[subentryID]
            encrypt = not entry["compressed_file_size"] == -2
            compress = not (entry["compressed_file_size"] == -1 or entry["compressed_file_size"] == -2)

            if self.verbose:
                print("Now reading file %s from sub-archive %s..." % (subentry["name"], entry["key"]))

            file = open(self.inPath + self.names.get_name(entry["key"]) + "_data/" + subentry["name"], "rb")
            files[subentryID] = file.read()
            file.close()

            original_filesize = len(files[subentryID])

            if compress:
                if self.verbose:
                    print("Compressing file...")

                files[subentryID] = zlib.compress(files[subentryID])
                files[subentryID] += self.__add_padding(len(files[subentryID]))

            if encrypt:
                if self.verbose:
                    print("Encrypting file...")

                for i in range(0, min(len(files[subentryID]), 0x100), 0x10):
                    files[subentryID] = Encryption.get_chunk(key, files[subentryID], i, 0xA)

            if self.verbose:
                print("Writing subentry header...")

            final_filesize = len(files[subentryID])
            use_size = final_filesize if entry["compressed_file_size"] > 0 else entry["compressed_file_size"]
            self.__write_subentry_header(pkg, subentry, original_filesize, use_size)

        return files, entries
```

**Comment by GrzybDev** [comment]
Hi, thank you for reporting.
Seems like you're on good path with fixing that bug, I'll check it in my own environment to see, and I'll make update if it's real cause (seems like just typo, haha)

**Comment by gledson999** [comment]
I have some issue to report, some pack does extract, but if you try to pack, cause some error like this:
![image](https://user-images.githubusercontent.com/31073450/117736369-c9fac900-b1cd-11eb-9f0b-0ee7dc451471.png)

If you extract this and repack, this pack below, cause the error:
bbs_second.pkg
bbs_fourth.pkg

This pkg doesn't extract, and freeze the pc, I waited 4 hour and no success
kh1_second.pkg
