### ISSUE TITLE
Wildcards aren't working

### ISSUE THREAD

**Issue by adamboy7** [GrzybDev/KingdomHeartsTool#17]
**Describe the bug**
While trying to bulk extract all .hed files in a folder, using wildcards causes a traceback and the program crashes. If I pass it a specific file like "khtool -u "C:\Users\Adam\Desktop\KH2\kh2_first.hed" -o "C:\Users\Adam\Desktop\KH2\Out"", it dumps the file just fine.

**To Reproduce**
1. Install the program using "pip install KingdomHeartsTool-2.0-py3-none-any.whl"
2. Run the command "khtool -u "C:\Users\Adam\Desktop\KH2\*.hed" -o "C:\Users\Adam\Desktop\KH2\Out""
3. Receive "OSError: [Errno 22] Invalid argument: 'C:\\Users\\Adam\\Desktop\\KH2\\*.hed'"

**Expected behavior**
khtool opens all .hed files and dumps their contents into the specified out folder.

**Screenshots**
Directory with files:
![image](https://user-images.githubusercontent.com/4840111/122321775-6a8d8880-cef2-11eb-8fa4-788bac939203.png)

Single file:
![image](https://user-images.githubusercontent.com/4840111/122320664-9871cd80-cef0-11eb-9849-29fbb7a0de2f.png)

Wildcard:
![image](https://user-images.githubusercontent.com/4840111/122320753-c2c38b00-cef0-11eb-8f20-5264390c0263.png)

Just to see if it was a windows only issue, I tried installing and running on WSL and received similar issues:
![image](https://user-images.githubusercontent.com/4840111/122321665-387c2680-cef2-11eb-839f-a6c55b36ce63.png)

**Desktop:**
 - Windows 10
 - OS Build 19042.1052
 - Command Prompt

**Comment by GrzybDev** [comment]
Hello, thanks for your report.

I removed wildcard support from unpack and pack tool due to code redesign, but if you want to unpack multiple files (i.e all archives in folder) just provide folder path, it should work. If it doesn't please respond, and if it works i'm considering this as closed issue, so make sure you close it :)

**Comment by GrzybDev** [comment]
Ahh, now i know why you tried wildcards, i forgot to update README.md, i'm really sorry for that, will update is as fast as possible

**Comment by adamboy7** [comment]
Not a problem, it happens! Thank you for your program and for taking the time to look into it :)
