### ISSUE TITLE
Accent not function

### ISSUE THREAD

**Issue by guitutilo** [GrzybDev/KingdomHeartsTool#7]
Versions: 1.2.1
I verified that when compiling bbs_first.pkg the accents were with X as shown in the image below:
https://ibb.co/xfLc7P2

If I use the original bbs_first.pkg file the accent goes back:
https://ibb.co/41HT7qX

It may be that in the encoding you did not put UTF-16

**Comment by GrzybDev** [comment]
You need to use replace table, because the game does not understand that

**Comment by guitutilo** [comment]
How to use? Could you give me an example? Or put it in the readme?

**Comment by GrzybDev** [comment]
You have example in replace_table.json

**Comment by guitutilo** [comment]
I tried doing it like that, because I didn't understand your example very well:
python -m khtool -v -l "replace_table.json" -r traduzir/output/SettingMenu/BEB2DD13552A07B1BAC2E1FC4DCD6837.po

**Comment by guitutilo** [comment]
And nothing happened, nothing changed

**Comment by GrzybDev** [comment]
But... you created your replace table for your language?

**Comment by guitutilo** [comment]
Yes, I'm trying to make some accents, but I didn't see any changes. Is it correct to use replace_table.json as I informed above?

**Comment by GrzybDev** [comment]
Yes

**Comment by guitutilo** [comment]
I have the accent "á", I put it as in the replace table then? "a": "á"?

**Comment by guitutilo** [comment]
ok, but "á" is supported in the Spanish language, so it should appear, don't you think?

**Comment by GrzybDev** [comment]
You didn't provided any information about your input files, i've got only your screenshots. So i've assumed you modified files with.

**Comment by guitutilo** [comment]
I didn't change anything just extract it then compiled it without modification and didn't get the accentuation.

**Comment by GrzybDev** [comment]
Gosh, i specifically requested 3 things, you only provided one. I need to know what my tool does wrong, without original and modified i cannot check compare these files...

**Comment by GrzybDev** [comment]
Also, as i specifically told you, my tool is designed only for english locale files... Others are supported without ANY warranty
